/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableCellRenderer;
import dao.CategorieDAO;
import dao.ProduitDAO;
import model.Categorie;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

/**
 *
 * @author logos
 */
public class GestionCategoriesForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionCategoriesForm.class.getName());

    private CategorieDAO categorieDAO;
    private ProduitDAO produitDAO;
    
    // Modèle de tableau
    private DefaultTableModel tableModel;
    
    // État courant
    private boolean modeAjout = true;
    private int categorieSelectionneeId = -1;
    
    /**
     * Creates new form GestionCategoriesForm
     */
    public GestionCategoriesForm() {
        initComponents();
        setupInterface();
        initialiserDonnees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpoutils = new javax.swing.JPanel();
        jbajouter = new javax.swing.JButton();
        jbmodifier = new javax.swing.JButton();
        jbsupprimer = new javax.swing.JButton();
        jbactualiser = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jttablecategories = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jllibelle = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jltitreformulaire = new javax.swing.JLabel();
        jbenregistrer = new javax.swing.JButton();
        jbannuler = new javax.swing.JButton();
        jbreinitialiser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("\"Gestion des Catégories - Restaurant Management");
        setSize(new java.awt.Dimension(700, 600));

        jbajouter.setBackground(new java.awt.Color(0, 255, 0));
        jbajouter.setText("Ajouter");
        jbajouter.addActionListener(this::jbajouterActionPerformed);

        jbmodifier.setBackground(new java.awt.Color(102, 102, 255));
        jbmodifier.setText("Modifier");
        jbmodifier.addActionListener(this::jbmodifierActionPerformed);

        jbsupprimer.setBackground(new java.awt.Color(255, 0, 0));
        jbsupprimer.setText("Supprimer");
        jbsupprimer.addActionListener(this::jbsupprimerActionPerformed);

        jbactualiser.setBackground(new java.awt.Color(255, 255, 51));
        jbactualiser.setText("Actualiser");
        jbactualiser.addActionListener(this::jbactualiserActionPerformed);

        javax.swing.GroupLayout jpoutilsLayout = new javax.swing.GroupLayout(jpoutils);
        jpoutils.setLayout(jpoutilsLayout);
        jpoutilsLayout.setHorizontalGroup(
            jpoutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpoutilsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbajouter)
                .addGap(61, 61, 61)
                .addComponent(jbmodifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbsupprimer)
                .addGap(75, 75, 75)
                .addComponent(jbactualiser)
                .addGap(58, 58, 58))
        );
        jpoutilsLayout.setVerticalGroup(
            jpoutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpoutilsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpoutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbajouter)
                    .addComponent(jbmodifier)
                    .addComponent(jbsupprimer)
                    .addComponent(jbactualiser))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jttablecategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Libelle", "Nb produits", "Actions"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jttablecategories.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jttablecategories.setGridColor(new java.awt.Color(211, 211, 211));
        jttablecategories.setRowHeight(30);
        jttablecategories.setSelectionBackground(new java.awt.Color(173, 216, 230));
        jttablecategories.setShowHorizontalLines(true);
        jttablecategories.setShowVerticalLines(true);
        jttablecategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jttablecategoriesMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(jttablecategories);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jllibelle.setText("Libellé :");

        jLabel1.setText("\"(doit être unique)\"");

        jltitreformulaire.setText("FORMULAIRE CATEGORIE");

        jbenregistrer.setText("Enregistrer");
        jbenregistrer.addActionListener(this::jbenregistrerActionPerformed);

        jbannuler.setText("Annuler");
        jbannuler.addActionListener(this::jbannulerActionPerformed);

        jbreinitialiser.setText("Réinitialiser");
        jbreinitialiser.addActionListener(this::jbreinitialiserActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jllibelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jltitreformulaire)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jbenregistrer)
                .addGap(48, 48, 48)
                .addComponent(jbannuler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbreinitialiser)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltitreformulaire)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jllibelle)
                    .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbenregistrer)
                    .addComponent(jbannuler)
                    .addComponent(jbreinitialiser))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpoutils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpoutils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupInterface() {
        // Centrer la fenêtre
        setLocationRelativeTo(null);
        
        // Initialiser les DAOs
        categorieDAO = new CategorieDAO();
        produitDAO = new ProduitDAO();
        
        // Configurer le modèle de tableau
        configurerTableau();
        
        // Charger les données
        chargerCategories();
        
        // Ajouter les tooltips
        ajouterToolTips();
        
        // Initialiser en mode ajout
        activerModeAjout();
        
        // Personnaliser les curseurs
        personnaliserCurseurs();
    }
    
    private void configurerTableau() {
        tableModel = (DefaultTableModel) jttablecategories.getModel();
        tableModel.setRowCount(0); // Vider le tableau
        
        // Configurer les largeurs de colonnes
        jttablecategories.getColumnModel().getColumn(0).setPreferredWidth(50);   // ID
        jttablecategories.getColumnModel().getColumn(1).setPreferredWidth(250);  // Libellé
        jttablecategories.getColumnModel().getColumn(2).setPreferredWidth(100);  // Nb Produits
        jttablecategories.getColumnModel().getColumn(3).setPreferredWidth(80);   // Actions
        
        // Centrer le texte dans certaines colonnes
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jttablecategories.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jttablecategories.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jttablecategories.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    }
    
    private void chargerCategories() {
        try {
            tableModel.setRowCount(0); // Vider le tableau
            
            List<Categorie> categories = categorieDAO.getAllCategories();
            for (Categorie categorie : categories) {
                // Compter le nombre de produits par catégorie
                int nbProduits = produitDAO.getProduitsByCategorie(categorie.getId()).size();
                
                // Ajouter une ligne au tableau
                tableModel.addRow(new Object[]{
                    categorie.getId(),
                    categorie.getLibelle(),
                    nbProduits,
                    "✏️"  // Bouton d'action
                });
            }
            
            if (tableModel.getRowCount() == 0) {
                logger.info("Aucune catégorie trouvée dans la base de données");
            } else {
                logger.info(tableModel.getRowCount() + " catégories chargées");
            }
        } catch (Exception e) {
            logger.severe("Erreur lors du chargement des catégories: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur lors du chargement des catégories: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ajouterToolTips() {
        // Boutons de la barre d'outils
        jbajouter.setToolTipText("<html><b>Ajouter une nouvelle catégorie</b><br>Remplissez le formulaire ci-dessous</html>");
        jbmodifier.setToolTipText("<html><b>Modifier la catégorie sélectionnée</b><br>Sélectionnez d'abord une catégorie dans le tableau</html>");
        jbsupprimer.setToolTipText("<html><b>Supprimer la catégorie sélectionnée</b><br>Sélectionnez d'abord une catégorie dans le tableau</html>");
        jbactualiser.setToolTipText("<html><b>Actualiser la liste des catégories</b><br>Recharger les données depuis la base</html>");
        
        // Champs du formulaire
        txtLibelle.setToolTipText("<html><b>Nom de la catégorie</b><br>• Champ obligatoire<br>• Doit être unique</html>");
        
        // Boutons du formulaire
        jbenregistrer.setToolTipText("<html><b>Enregistrer les modifications</b><br>Valider le formulaire</html>");
        jbannuler.setToolTipText("<html><b>Annuler les modifications</b><br>Vider le formulaire</html>");
        jbreinitialiser.setToolTipText("<html><b>Réinitialiser le formulaire</b><br>Remettre à zéro tous les champs</html>");
        
        // Tableau
        jttablecategories.setToolTipText("<html><b>Liste des catégories</b><br>• Double-cliquez sur une ligne pour la modifier<br>• Cliquez sur ✏️ pour modifier<br>• Cliquez une fois pour sélectionner</html>");
    }
    
    private void personnaliserCurseurs() {
        // Boutons de la barre d'outils
        jbajouter.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbmodifier.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbsupprimer.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbactualiser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        // Boutons du formulaire
        jbenregistrer.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbannuler.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbreinitialiser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        // Tableau
        jttablecategories.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    
    private void activerModeAjout() {
        modeAjout = true;
        categorieSelectionneeId = -1;
        jbenregistrer.setText("Ajouter");
        jbenregistrer.setBackground(new Color(39, 174, 96)); // Vert
        reinitialiserFormulaire();
        jttablecategories.clearSelection();
    }
    
    private void activerModeModification(int id) {
        modeAjout = false;
        categorieSelectionneeId = id;
        jbenregistrer.setText("Modifier");
        jbenregistrer.setBackground(new Color(52, 152, 219)); // Bleu
    }
    
    private void reinitialiserFormulaire() {
        txtLibelle.setText("");
    }
    
    private boolean validerFormulaire() {
        // Validation du libellé
        String libelle = txtLibelle.getText().trim();
        
        if (libelle.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un libellé pour la catégorie.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            txtLibelle.requestFocus();
            return false;
        }
        
        if (libelle.length() < 2) {
            JOptionPane.showMessageDialog(this, 
                "Le libellé doit contenir au moins 2 caractères.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            txtLibelle.requestFocus();
            return false;
        }
        
        // Vérifier si le libellé existe déjà (sauf en mode modification)
        if (modeAjout || !libelle.equals(getLibelleCategorieSelectionnee())) {
            try {
                if (categorieDAO.libelleExists(libelle)) {
                    JOptionPane.showMessageDialog(this, 
                        "Ce libellé existe déjà. Veuillez en choisir un autre.",
                        "Erreur de validation",
                        JOptionPane.ERROR_MESSAGE);
                    txtLibelle.requestFocus();
                    txtLibelle.selectAll();
                    return false;
                }
            } catch (Exception e) {
                logger.warning("Impossible de vérifier l'unicité du libellé: " + e.getMessage());
            }
        }
        
        return true;
    }
    
    private String getLibelleCategorieSelectionnee() {
        try {
            Categorie categorie = categorieDAO.getCategorieById(categorieSelectionneeId);
            return categorie != null ? categorie.getLibelle() : "";
        } catch (Exception e) {
            return "";
        }
    }
    
    private void enregistrerCategorie() {
        if (!validerFormulaire()) {
            return;
        }
        
        try {
            String libelle = txtLibelle.getText().trim();
            Categorie categorie = new Categorie(libelle);
            
            boolean success;
            String message;
            
            if (modeAjout) {
                // Mode ajout
                success = categorieDAO.addCategorie(categorie);
                message = success ? "Catégorie ajoutée avec succès!" : "Erreur lors de l'ajout de la catégorie.";
            } else {
                // Mode modification
                categorie.setId(categorieSelectionneeId);
                success = categorieDAO.updateCategorie(categorie);
                message = success ? "Catégorie modifiée avec succès!" : "Erreur lors de la modification de la catégorie.";
            }
            
            if (success) {
                JOptionPane.showMessageDialog(this, message, "Succès", JOptionPane.INFORMATION_MESSAGE);
                chargerCategories();
                activerModeAjout();
            } else {
                JOptionPane.showMessageDialog(this, message, "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            logger.severe("Erreur lors de l'enregistrement de la catégorie: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur lors de l'enregistrement: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void supprimerCategorie() {
        int selectedRow = jttablecategories.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner une catégorie à supprimer.",
                "Aucune sélection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Convertir l'index de la vue à l'index du modèle
        int modelRow = jttablecategories.convertRowIndexToModel(selectedRow);
        int id = (int) tableModel.getValueAt(modelRow, 0);
        String libelle = (String) tableModel.getValueAt(modelRow, 1);
        int nbProduits = (int) tableModel.getValueAt(modelRow, 2);
        
        // Vérifier si la catégorie contient des produits
        if (nbProduits > 0) {
            JOptionPane.showMessageDialog(this,
                "Impossible de supprimer cette catégorie car elle contient " + nbProduits + " produit(s).\n" +
                "Veuillez d'abord supprimer ou déplacer les produits de cette catégorie.",
                "Catégorie non vide",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirmation = JOptionPane.showConfirmDialog(this,
            "Êtes-vous sûr de vouloir supprimer la catégorie :\n\"" + libelle + "\"?",
            "Confirmation de suppression",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirmation == JOptionPane.YES_OPTION) {
            try {
                boolean success = categorieDAO.deleteCategorie(id);
                if (success) {
                    JOptionPane.showMessageDialog(this,
                        "Catégorie supprimée avec succès!",
                        "Succès",
                        JOptionPane.INFORMATION_MESSAGE);
                    chargerCategories();
                    activerModeAjout();
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Erreur lors de la suppression de la catégorie.",
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                logger.severe("Erreur lors de la suppression de la catégorie: " + e.getMessage());
                JOptionPane.showMessageDialog(this,
                    "Erreur lors de la suppression: " + e.getMessage(),
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void remplirFormulaireDepuisTableau() {
        int selectedRow = jttablecategories.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        
        // Convertir l'index de la vue à l'index du modèle
        int modelRow = jttablecategories.convertRowIndexToModel(selectedRow);
        int id = (int) tableModel.getValueAt(modelRow, 0);
        String libelle = (String) tableModel.getValueAt(modelRow, 1);
        
        // Remplir le formulaire
        txtLibelle.setText(libelle);
        
        // Activer le mode modification
        activerModeModification(id);
    }
    
    
    private void jbactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbactualiserActionPerformed
        chargerCategories();
        JOptionPane.showMessageDialog(this,
            "Liste des catégories actualisée.",
            "Actualisation",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbactualiserActionPerformed

    private void jbajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbajouterActionPerformed
        activerModeAjout();
    }//GEN-LAST:event_jbajouterActionPerformed

    private void jbmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodifierActionPerformed
        remplirFormulaireDepuisTableau();
        
        if (categorieSelectionneeId == -1) {
            JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner une catégorie à modifier.",
                "Aucune sélection",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbmodifierActionPerformed

    private void jbsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsupprimerActionPerformed
        supprimerCategorie();
    }//GEN-LAST:event_jbsupprimerActionPerformed

    private void jbenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbenregistrerActionPerformed
        enregistrerCategorie();
    }//GEN-LAST:event_jbenregistrerActionPerformed

    private void jbannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbannulerActionPerformed
        activerModeAjout();
        JOptionPane.showMessageDialog(this,
            "Opération annulée. Formulaire réinitialisé.",
            "Annulation",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbannulerActionPerformed

    private void jbreinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreinitialiserActionPerformed
        reinitialiserFormulaire();
    }//GEN-LAST:event_jbreinitialiserActionPerformed

    private void jttablecategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jttablecategoriesMouseClicked
        int column = jttablecategories.columnAtPoint(evt.getPoint());
        int row = jttablecategories.rowAtPoint(evt.getPoint());
        
        if (row >= 0 && column >= 0) {
            // Si c'est un double-clic n'importe où sur la ligne
            if (evt.getClickCount() == 2) {
                remplirFormulaireDepuisTableau();
            }
            // Si c'est un clic simple sur la colonne "Actions" (colonne 3)
            else if (column == 3) {
                remplirFormulaireDepuisTableau();
            }
        }
    }//GEN-LAST:event_jttablecategoriesMouseClicked

    
    private void initialiserDonnees() {
        // Vérifier la connexion à la base
        try {
            chargerCategories();
            logger.info("GestionCategoriesForm initialisé avec succès");
        } catch (Exception e) {
            logger.severe("Erreur d'initialisation: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Impossible de se connecter à la base de données.\n" +
                "Veuillez vérifier que MySQL est démarré.\n\n" +
                "Erreur: " + e.getMessage(),
                "Erreur de connexion",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        // Utiliser le look and feel système
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            logger.log(java.util.logging.Level.WARNING, null, e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            GestionCategoriesForm form = new GestionCategoriesForm();
            form.setLocationRelativeTo(null); // Centrer la fenêtre
            form.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton jbactualiser;
    private javax.swing.JButton jbajouter;
    private javax.swing.JButton jbannuler;
    private javax.swing.JButton jbenregistrer;
    private javax.swing.JButton jbmodifier;
    private javax.swing.JButton jbreinitialiser;
    private javax.swing.JButton jbsupprimer;
    private javax.swing.JLabel jllibelle;
    private javax.swing.JLabel jltitreformulaire;
    private javax.swing.JPanel jpoutils;
    private javax.swing.JTable jttablecategories;
    private javax.swing.JTextField txtLibelle;
    // End of variables declaration//GEN-END:variables
}
