/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.MouvementStockDAO;
import dao.ProduitDAO;
import model.MouvementStock;
import model.Produit;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author logos
 */
public class GestionStockForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionStockForm.class.getName());
    // DAOs
    private MouvementStockDAO mouvementDAO;
    private ProduitDAO produitDAO;
    
    // Modèle de tableau
    private DefaultTableModel tableModel;
    private TableRowSorter<DefaultTableModel> sorter;
    
    // Formatters
    private SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    
    // État courant
    private boolean modeEntree = true;
    
    /**
     * Creates new form GestionStockForm
     */
    public GestionStockForm() {
        initComponents();
        setupInterface();
        initialiserDonnees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbentree = new javax.swing.JButton();
        jbsortie = new javax.swing.JButton();
        jbactualiser = new javax.swing.JButton();
        jbproduitsalerte = new javax.swing.JButton();
        jlrechercher = new javax.swing.JLabel();
        txtRecherche = new javax.swing.JTextField();
        jbrechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMouvements = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jltype = new javax.swing.JLabel();
        jcbentresortie = new javax.swing.JComboBox<>();
        jlproduit = new javax.swing.JLabel();
        jcbproduit = new javax.swing.JComboBox<>();
        jlquantite = new javax.swing.JLabel();
        txtQuantite = new javax.swing.JTextField();
        jlmotif = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jbenregistrer = new javax.swing.JButton();
        jbannuler = new javax.swing.JButton();
        jbreinitialiser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion du Stock - Restaurant Management");
        setSize(new java.awt.Dimension(700, 900));

        jbentree.setText("ENTRÉE");
        jbentree.setToolTipText("Enregistrer une entrée de stock (augmente le stock)");
        jbentree.addActionListener(this::jbentreeActionPerformed);

        jbsortie.setText("SORTIE");
        jbsortie.setToolTipText("Enregistrer une sortie de stock (diminue le stock)");
        jbsortie.addActionListener(this::jbsortieActionPerformed);

        jbactualiser.setText("Actualiser");
        jbactualiser.addActionListener(this::jbactualiserActionPerformed);

        jbproduitsalerte.setText("Produits Alerte");
        jbproduitsalerte.setToolTipText("Voir les produits avec stock inférieur au seuil d'alerte");
        jbproduitsalerte.addActionListener(this::jbproduitsalerteActionPerformed);

        jlrechercher.setText("Rechercher :");

        jbrechercher.setText("🔍");
        jbrechercher.addActionListener(this::jbrechercherActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbentree)
                .addGap(18, 18, 18)
                .addComponent(jbsortie)
                .addGap(18, 18, 18)
                .addComponent(jbactualiser)
                .addGap(18, 18, 18)
                .addComponent(jbproduitsalerte)
                .addGap(23, 23, 23)
                .addComponent(jlrechercher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRecherche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbentree)
                    .addComponent(jbsortie)
                    .addComponent(jbactualiser)
                    .addComponent(jbproduitsalerte)
                    .addComponent(jlrechercher)
                    .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbrechercher))
                .addContainerGap())
        );

        tableMouvements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produits", "Type", "Quantité", "Date", "Motif"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMouvements.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableMouvements.setRowHeight(30);
        tableMouvements.setShowHorizontalLines(true);
        tableMouvements.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tableMouvements);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulaire Mouvement de Stock"));

        jltype.setText("Type :");

        jcbentresortie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTRÉE", "SORTIE" }));
        jcbentresortie.setToolTipText("Type de mouvement: ENTRÉE (ajoute) ou SORTIE (retire)");
        jcbentresortie.addActionListener(this::jcbentresortieActionPerformed);

        jlproduit.setText("Produit :");

        jcbproduit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbproduit.setToolTipText("Sélectionnez le produit concerné");
        jcbproduit.addActionListener(this::jcbproduitActionPerformed);

        jlquantite.setText("Quantité :");

        jlmotif.setText("Motif:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Achat", "Vente", "Inventaire", "Perte", "Don", "Autre" }));

        jbenregistrer.setText("Enregistrer");
        jbenregistrer.addActionListener(this::jbenregistrerActionPerformed);

        jbannuler.setText("Annuler");
        jbannuler.addActionListener(this::jbannulerActionPerformed);

        jbreinitialiser.setText("Réinitialiser");
        jbreinitialiser.addActionListener(this::jbreinitialiserActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jltype)
                            .addComponent(jlproduit)
                            .addComponent(jlquantite)
                            .addComponent(jlmotif))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbentresortie, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jbenregistrer)
                        .addGap(58, 58, 58)
                        .addComponent(jbannuler)
                        .addGap(65, 65, 65)
                        .addComponent(jbreinitialiser)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbentresortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jltype))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbproduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlproduit))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlquantite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlmotif)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbenregistrer)
                    .addComponent(jbannuler)
                    .addComponent(jbreinitialiser))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setupInterface() {
        // Centrer la fenêtre
        setLocationRelativeTo(null);
        
        // Initialiser les DAOs
        mouvementDAO = new MouvementStockDAO();
        produitDAO = new ProduitDAO();
        
        // Configurer le modèle de tableau
        configurerTableau();
        
        // Charger les données
        chargerMouvements();
        chargerProduits();
        
        // Configurer les validations
        configurerValidations();
        
        // Ajouter les tooltips améliorés
        ajouterToolTips();
        
        // Configurer la recherche en temps réel
        configurerRecherche();
        
        // Initialiser en mode entrée
        activerModeEntree();
        
        // Personnaliser les curseurs
        personnaliserCurseurs();
    }
    
    private void configurerTableau() {
        tableModel = (DefaultTableModel) tableMouvements.getModel();
        tableModel.setRowCount(0); // Vider le tableau
        
        // Créer un RowSorter pour le tri et la recherche
        sorter = new TableRowSorter<>(tableModel);
        tableMouvements.setRowSorter(sorter);
        
        // Configurer les largeurs de colonnes
        tableMouvements.getColumnModel().getColumn(0).setPreferredWidth(50);   // ID
        tableMouvements.getColumnModel().getColumn(1).setPreferredWidth(200);  // Produit
        tableMouvements.getColumnModel().getColumn(2).setPreferredWidth(80);   // Type
        tableMouvements.getColumnModel().getColumn(3).setPreferredWidth(80);   // Quantité
        tableMouvements.getColumnModel().getColumn(4).setPreferredWidth(150);  // Date
        tableMouvements.getColumnModel().getColumn(5).setPreferredWidth(150);  // Motif
        
        // Centrer le texte dans certaines colonnes
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableMouvements.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tableMouvements.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tableMouvements.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        
        // Colorer les lignes selon le type
        tableMouvements.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                
                if (!isSelected) {
                    String type = (String) table.getValueAt(row, 2);
                    if ("ENTRÉE".equals(type)) {
                        c.setBackground(new Color(220, 255, 220)); // Vert clair
                    } else if ("SORTIE".equals(type)) {
                        c.setBackground(new Color(255, 220, 220)); // Rouge clair
                    } else {
                        c.setBackground(Color.WHITE);
                    }
                }
                return c;
            }
        });
    }
    
    
    private void chargerMouvements() {
        try {
            tableModel.setRowCount(0); // Vider le tableau
            
            List<MouvementStock> mouvements = mouvementDAO.getAllMouvements();
            for (MouvementStock mouvement : mouvements) {
                tableModel.addRow(new Object[]{
                    mouvement.getId(),
                    mouvement.getProduit().getNom(),
                    mouvement.getType(),
                    mouvement.getQuantite(),
                    dateFormat.format(mouvement.getDateMouvement()),
                    mouvement.getMotif()
                });
            }
            
            if (tableModel.getRowCount() == 0) {
                logger.info("Aucun mouvement de stock trouvé");
            } else {
                logger.info(tableModel.getRowCount() + " mouvements chargés");
            }
        } catch (Exception e) {
            logger.severe("Erreur lors du chargement des mouvements: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur lors du chargement des mouvements: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void chargerProduits() {
        try {
            jcbproduit.removeAllItems();
            jcbproduit.addItem("-- Sélectionnez un produit --");
            
            List<Produit> produits = produitDAO.getAllProduits();
            for (Produit produit : produits) {
                String item = produit.getNom() + " (Stock: " + produit.getStockActuel() + ")";
                jcbproduit.addItem(item);
                // Stocker l'ID du produit dans le client property
                jcbproduit.putClientProperty("produit_" + jcbproduit.getItemCount(), produit);
            }
            
            if (jcbproduit.getItemCount() == 1) {
                logger.warning("Aucun produit trouvé dans la base de données");
                JOptionPane.showMessageDialog(this, 
                    "Aucun produit trouvé.\nVeuillez d'abord créer des produits.",
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            logger.severe("Erreur lors du chargement des produits: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur lors du chargement des produits: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private Produit getProduitSelectionne() {
        int index = jcbproduit.getSelectedIndex();
        if (index > 0) {
            return (Produit) jcbproduit.getClientProperty("produit_" + index);
        }
        return null;
    }
    
    private void configurerValidations() {
        // Empêcher les lettres dans le champ quantité
        txtQuantite.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
                    e.consume();
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }
    
    private void ajouterToolTips() {
        // Boutons de la barre d'outils
        jbentree.setToolTipText("<html><b>Enregistrer une entrée de stock</b><br>Augmente le stock disponible</html>");
        jbsortie.setToolTipText("<html><b>Enregistrer une sortie de stock</b><br>Diminue le stock disponible</html>");
        jbactualiser.setToolTipText("<html><b>Actualiser la liste des mouvements</b><br>Recharger les données depuis la base</html>");
        jbproduitsalerte.setToolTipText("<html><b>Afficher les produits en alerte</b><br>Produits avec stock inférieur au seuil d'alerte</html>");
        jbrechercher.setToolTipText("<html><b>Rechercher un mouvement</b><br>Par produit, type ou motif</html>");
        
        // Champs du formulaire
        jcbentresortie.setToolTipText("<html><b>Type de mouvement</b><br>• ENTRÉE: ajoute au stock<br>• SORTIE: retire du stock</html>");
        jcbproduit.setToolTipText("<html><b>Produit concerné</b><br>Sélectionnez un produit dans la liste<br>Affiche le stock actuel</html>");
        txtQuantite.setToolTipText("<html><b>Quantité</b><br>• Doit être supérieure à 0<br>• Pour les sorties, ne peut pas dépasser le stock disponible</html>");
        jComboBox2.setToolTipText("<html><b>Motif du mouvement</b><br>Raison de l'entrée ou sortie de stock</html>");
        txtRecherche.setToolTipText("<html><b>Recherche rapide</b><br>• Tapez pour rechercher par produit, type ou motif<br>• La recherche est instantanée</html>");
        
        // Boutons du formulaire
        jbenregistrer.setToolTipText("<html><b>Enregistrer le mouvement</b><br>Valider le formulaire</html>");
        jbannuler.setToolTipText("<html><b>Annuler l'opération</b><br>Vider le formulaire</html>");
        jbreinitialiser.setToolTipText("<html><b>Réinitialiser le formulaire</b><br>Remettre à zéro tous les champs</html>");
        
        // Tableau
        tableMouvements.setToolTipText("<html><b>Historique des mouvements de stock</b><br>• Entrées en vert clair<br>• Sorties en rouge clair<br>• Double-cliquez pour voir les détails</html>");
    }
    
    private void configurerRecherche() {
        // Recherche en temps réel
        txtRecherche.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrerTableau();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrerTableau();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrerTableau();
            }
        });
    }
    
    private void filtrerTableau() {
        String texte = txtRecherche.getText().toLowerCase();
        if (texte.trim().isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texte, 1, 2, 5)); // Colonnes Produit, Type, Motif
        }
    }
    
    private void personnaliserCurseurs() {
        // Boutons de la barre d'outils
        jbentree.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbsortie.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbactualiser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbproduitsalerte.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbrechercher.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        // Boutons du formulaire
        jbenregistrer.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbannuler.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jbreinitialiser.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private void activerModeEntree() {
        modeEntree = true;
        jcbentresortie.setSelectedItem("ENTRÉE");
        jbentree.setBackground(new Color(46, 204, 113)); // Vert
        jbsortie.setBackground(new Color(230, 126, 34)); // Orange normal
        logger.info("Mode Entrée activé");
    }
    
    private void activerModeSortie() {
        modeEntree = false;
        jcbentresortie.setSelectedItem("SORTIE");
        jbsortie.setBackground(new Color(210, 106, 24)); // Orange foncé
        jbentree.setBackground(new Color(36, 194, 103)); // Vert normal
        logger.info("Mode Sortie activé");
    }
    
    private void reinitialiserFormulaire() {
        jcbproduit.setSelectedIndex(0);
        txtQuantite.setText("");
        jComboBox2.setSelectedIndex(0);
        logger.info("Formulaire réinitialisé");
    }
    
    private boolean validerFormulaire() {
        // Validation du type
        if (jcbentresortie.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner un type de mouvement.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            jcbentresortie.requestFocus();
            return false;
        }
        
        // Validation du produit
        if (jcbproduit.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner un produit.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            jcbproduit.requestFocus();
            return false;
        }
        
        // Validation de la quantité
        try {
            String quantiteText = txtQuantite.getText().trim();
            if (quantiteText.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Veuillez saisir une quantité.",
                    "Erreur de validation",
                    JOptionPane.ERROR_MESSAGE);
                txtQuantite.requestFocus();
                return false;
            }
            
            int quantite = Integer.parseInt(quantiteText);
            if (quantite <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "La quantité doit être supérieure à 0.",
                    "Erreur de validation",
                    JOptionPane.ERROR_MESSAGE);
                txtQuantite.requestFocus();
                return false;
            }
            
            // Pour les sorties, vérifier le stock disponible
            if ("SORTIE".equals(jcbentresortie.getSelectedItem())) {
                Produit produit = getProduitSelectionne();
                if (produit != null) {
                    if (quantite > produit.getStockActuel()) {
                        JOptionPane.showMessageDialog(this, 
                            "Stock insuffisant!\n" +
                            "Stock disponible: " + produit.getStockActuel() + "\n" +
                            "Quantité demandée: " + quantite,
                            "Erreur de stock",
                            JOptionPane.ERROR_MESSAGE);
                        txtQuantite.requestFocus();
                        txtQuantite.selectAll();
                        return false;
                    }
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "La quantité doit être un nombre entier valide.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            txtQuantite.requestFocus();
            txtQuantite.selectAll();
            return false;
        }
        
        return true;
    }
    
    private void initialiserDonnees() {
        // Charger les données initiales
        SwingUtilities.invokeLater(() -> {
            chargerMouvements();
            chargerProduits();
        });
    }
    
    private void jbentreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbentreeActionPerformed
        activerModeEntree();
    }//GEN-LAST:event_jbentreeActionPerformed

    private void jbsortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsortieActionPerformed
        activerModeSortie();
    }//GEN-LAST:event_jbsortieActionPerformed

    private void jbactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbactualiserActionPerformed
        chargerMouvements();
        chargerProduits();
        JOptionPane.showMessageDialog(this, 
            "Données actualisées avec succès!",
            "Actualisation",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbactualiserActionPerformed

    private void jbproduitsalerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbproduitsalerteActionPerformed
        try {
            List<Produit> produitsAlerte = produitDAO.getProduitsEnAlerte();
            if (produitsAlerte.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Aucun produit en alerte de stock.",
                    "Produits en Alerte",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                StringBuilder message = new StringBuilder();
                message.append("<html><b>Produits avec stock faible:</b><br><br>");
                for (Produit produit : produitsAlerte) {
                    message.append("• ").append(produit.getNom())
                           .append(" - Stock: ").append(produit.getStockActuel())
                           .append(" (Seuil: ").append(produit.getSeuilAlerte()).append(")<br>");
                }
                message.append("</html>");
                
                JOptionPane.showMessageDialog(this,
                    message.toString(),
                    "⚠️ Produits en Alerte",
                    JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            logger.severe("Erreur lors de la récupération des produits en alerte: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbproduitsalerteActionPerformed

    private void jbrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrechercherActionPerformed
        txtRecherche.requestFocus();
        txtRecherche.selectAll();
    }//GEN-LAST:event_jbrechercherActionPerformed

    private void jcbentresortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbentresortieActionPerformed
        String type = (String) jcbentresortie.getSelectedItem();
        if ("ENTRÉE".equals(type)) {
            activerModeEntree();
        } else if ("SORTIE".equals(type)) {
            activerModeSortie();
        }
    }//GEN-LAST:event_jcbentresortieActionPerformed

    private void jcbproduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbproduitActionPerformed
        // Mettre à jour l'affichage si nécessaire
        Produit produit = getProduitSelectionne();
        if (produit != null) {
            logger.info("Produit sélectionné: " + produit.getNom() + " - Stock: " + produit.getStockActuel());
        }
    }//GEN-LAST:event_jcbproduitActionPerformed

    private void jbenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbenregistrerActionPerformed
        if (!validerFormulaire()) {
            return;
        }
        
        try {
            // Récupérer les données du formulaire
            Produit produit = getProduitSelectionne();
            String type = (String) jcbentresortie.getSelectedItem();
            int quantite = Integer.parseInt(txtQuantite.getText().trim());
            String motif = (String) jComboBox2.getSelectedItem();
            Date date = new Date(); // Date actuelle
            
            // Créer le mouvement
            MouvementStock mouvement = new MouvementStock();
            mouvement.setProduit(produit);
            mouvement.setType(type);
            mouvement.setQuantite(quantite);
            mouvement.setMotif(motif);
            mouvement.setDateMouvement(date);
            
            // Enregistrer en base
            mouvementDAO.addMouvement(mouvement);
            
            // Mettre à jour le stock du produit
            produit.setStockActuel(produit.getStockActuel() + 
                ("ENTRÉE".equals(type) ? quantite : -quantite));
            produitDAO.updateProduit(produit);
            
            // Actualiser l'affichage
            chargerMouvements();
            chargerProduits();
            reinitialiserFormulaire();
            
            // Message de confirmation
            JOptionPane.showMessageDialog(this,
                "Mouvement enregistré avec succès!\n" +
                "Produit: " + produit.getNom() + "\n" +
                "Type: " + type + "\n" +
                "Quantité: " + quantite + "\n" +
                "Nouveau stock: " + produit.getStockActuel(),
                "Succès",
                JOptionPane.INFORMATION_MESSAGE);
                
            logger.info("Mouvement enregistré: " + produit.getNom() + " - " + type + " - " + quantite);
            
        } catch (Exception e) {
            logger.severe("Erreur lors de l'enregistrement: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur lors de l'enregistrement: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbenregistrerActionPerformed

    private void jbannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbannulerActionPerformed
        int confirmation = JOptionPane.showConfirmDialog(this,
            "Voulez-vous vraiment annuler cette opération?",
            "Confirmation d'annulation",
            JOptionPane.YES_NO_OPTION);
            
        if (confirmation == JOptionPane.YES_OPTION) {
            reinitialiserFormulaire();
            logger.info("Opération annulée");
        }
    }//GEN-LAST:event_jbannulerActionPerformed

    private void jbreinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreinitialiserActionPerformed
         reinitialiserFormulaire();
    }//GEN-LAST:event_jbreinitialiserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionStockForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbactualiser;
    private javax.swing.JButton jbannuler;
    private javax.swing.JButton jbenregistrer;
    private javax.swing.JButton jbentree;
    private javax.swing.JButton jbproduitsalerte;
    private javax.swing.JButton jbrechercher;
    private javax.swing.JButton jbreinitialiser;
    private javax.swing.JButton jbsortie;
    private javax.swing.JComboBox<String> jcbentresortie;
    private javax.swing.JComboBox<String> jcbproduit;
    private javax.swing.JLabel jlmotif;
    private javax.swing.JLabel jlproduit;
    private javax.swing.JLabel jlquantite;
    private javax.swing.JLabel jlrechercher;
    private javax.swing.JLabel jltype;
    private javax.swing.JTable tableMouvements;
    private javax.swing.JTextField txtQuantite;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
