/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ProduitDAO;
import dao.CategorieDAO;
import model.Produit;
import model.Categorie;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author logos
 */
public class GestionProduitsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionProduitsForm.class.getName());
    // DAOs
    private ProduitDAO produitDAO;
    private CategorieDAO categorieDAO;
    
    // Modèle de tableau
    private DefaultTableModel tableModel;
    private TableRowSorter<DefaultTableModel> sorter;
    
    // État courant
    private boolean modeAjout = true;
    private int produitSelectionneId = -1;
    
    /**
     * Creates new form GestionProduitsForm
     */
    public GestionProduitsForm() {
        initComponents();
        setupInterface();
        initialiserDonnees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbajouter = new javax.swing.JButton();
        jbmodifier = new javax.swing.JButton();
        jbsupprimer = new javax.swing.JButton();
        jbactualiser = new javax.swing.JButton();
        jlrechercher = new javax.swing.JLabel();
        jtrechercher = new javax.swing.JTextField();
        jbrechercher = new javax.swing.JButton();
        jscrollPane = new javax.swing.JScrollPane();
        jttableproduits = new javax.swing.JTable();
        jpformulaire = new javax.swing.JPanel();
        jlnom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jlcatégorie = new javax.swing.JLabel();
        jccategorie = new javax.swing.JComboBox<>();
        jlprix = new javax.swing.JLabel();
        txtPrix = new javax.swing.JTextField();
        jlstock = new javax.swing.JLabel();
        jlFCFA = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jlUnités = new javax.swing.JLabel();
        jlSeuilalerte = new javax.swing.JLabel();
        txtSeuilAlerte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbenregistrer = new javax.swing.JButton();
        jbannuler = new javax.swing.JButton();
        jbreinitialiser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des Produits - Restaurant Management");
        setSize(new java.awt.Dimension(800, 600));

        jbajouter.setBackground(new java.awt.Color(46, 204, 113));
        jbajouter.setText("Ajouter");
        jbajouter.setFocusPainted(false);
        jbajouter.addActionListener(this::jbajouterActionPerformed);

        jbmodifier.setBackground(new java.awt.Color(52, 152, 219));
        jbmodifier.setText("Modifier");
        jbmodifier.setFocusPainted(false);
        jbmodifier.addActionListener(this::jbmodifierActionPerformed);

        jbsupprimer.setBackground(new java.awt.Color(231, 76, 60));
        jbsupprimer.setText("Supprimer");
        jbsupprimer.setFocusPainted(false);
        jbsupprimer.addActionListener(this::jbsupprimerActionPerformed);

        jbactualiser.setBackground(new java.awt.Color(241, 196, 15));
        jbactualiser.setText("Actualiser");
        jbactualiser.setFocusPainted(false);
        jbactualiser.addActionListener(this::jbactualiserActionPerformed);

        jlrechercher.setText("Rechercher :");
        jlrechercher.setToolTipText("");

        jbrechercher.setBackground(new java.awt.Color(149, 165, 166));
        jbrechercher.setText("🔍");
        jbrechercher.setFocusPainted(false);
        jbrechercher.addActionListener(this::jbrechercherActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbsupprimer)
                .addGap(18, 18, 18)
                .addComponent(jbactualiser)
                .addGap(18, 18, 18)
                .addComponent(jlrechercher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbrechercher)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbajouter)
                    .addComponent(jbmodifier)
                    .addComponent(jbsupprimer)
                    .addComponent(jbactualiser)
                    .addComponent(jlrechercher)
                    .addComponent(jtrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbrechercher))
                .addContainerGap())
        );

        jscrollPane.setBackground(new java.awt.Color(0, 204, 204));

        jttableproduits.setAutoCreateRowSorter(true);
        jttableproduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Categorie", "Prix(FCFA)", "Stock", "Seuil alerte", "Statut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jttableproduits.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jttableproduits.setGridColor(new java.awt.Color(211, 211, 211));
        jttableproduits.setRowHeight(25);
        jttableproduits.setSelectionBackground(new java.awt.Color(173, 216, 230));
        jttableproduits.setShowHorizontalLines(true);
        jttableproduits.setShowVerticalLines(true);
        jttableproduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jttableproduitsMouseClicked(evt);
            }
        });
        jscrollPane.setViewportView(jttableproduits);
        if (jttableproduits.getColumnModel().getColumnCount() > 0) {
            jttableproduits.getColumnModel().getColumn(0).setPreferredWidth(50);
            jttableproduits.getColumnModel().getColumn(1).setResizable(false);
            jttableproduits.getColumnModel().getColumn(1).setPreferredWidth(150);
            jttableproduits.getColumnModel().getColumn(2).setPreferredWidth(100);
            jttableproduits.getColumnModel().getColumn(3).setPreferredWidth(80);
            jttableproduits.getColumnModel().getColumn(4).setPreferredWidth(60);
            jttableproduits.getColumnModel().getColumn(5).setPreferredWidth(80);
            jttableproduits.getColumnModel().getColumn(6).setPreferredWidth(80);
        }

        jpformulaire.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpformulaire.setToolTipText("Formulaire Produit");
        jpformulaire.setAutoscrolls(true);

        jlnom.setText("<html>Nom: <font color='red'>*</font></html>");

        txtNom.addActionListener(this::txtNomActionPerformed);

        jlcatégorie.setText("<html>Catégorie: <font color='red'>*</font></html>");

        jccategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jccategorie.setToolTipText("Rechercher par nom ou catégorie");

        jlprix.setText("<html>Prix: <font color='red'>*</font></html>");

        jlstock.setText("<html>Stock: <font color='red'>*</font></html>");

        jlFCFA.setText("FCFA");

        txtStock.setToolTipText("Quantité actuelle en stock");

        jlUnités.setText("Unités");

        jlSeuilalerte.setText("Seuil alerte:");

        txtSeuilAlerte.setToolTipText("Seuil minimum avant alerte de réapprovisionnement");

        jLabel1.setText("(stock minimum)");

        jbenregistrer.setText("Enregistrer");
        jbenregistrer.setToolTipText("Enregistrer les modifications");
        jbenregistrer.addActionListener(this::jbenregistrerActionPerformed);

        jbannuler.setText("Annuler");
        jbannuler.setToolTipText("Annuler les modifications");
        jbannuler.addActionListener(this::jbannulerActionPerformed);

        jbreinitialiser.setText("Réinitialiser");
        jbreinitialiser.setToolTipText("Réinitialiser le formulaire");
        jbreinitialiser.addActionListener(this::jbreinitialiserActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jbenregistrer)
                .addGap(52, 52, 52)
                .addComponent(jbannuler)
                .addGap(40, 40, 40)
                .addComponent(jbreinitialiser)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbenregistrer)
                    .addComponent(jbannuler)
                    .addComponent(jbreinitialiser))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpformulaireLayout = new javax.swing.GroupLayout(jpformulaire);
        jpformulaire.setLayout(jpformulaireLayout);
        jpformulaireLayout.setHorizontalGroup(
            jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpformulaireLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcatégorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSeuilalerte)
                    .addComponent(jlprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jccategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpformulaireLayout.createSequentialGroup()
                        .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSeuilAlerte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrix, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlFCFA)
                            .addComponent(jlUnités)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpformulaireLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpformulaireLayout.setVerticalGroup(
            jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpformulaireLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcatégorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jccategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFCFA))
                .addGap(39, 39, 39)
                .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUnités))
                .addGap(41, 41, 41)
                .addGroup(jpformulaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSeuilalerte)
                    .addComponent(txtSeuilAlerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(74, 74, 74)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jscrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                            .addComponent(jpformulaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jscrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jpformulaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupInterface() {
        // Centrer la fenêtre
        setLocationRelativeTo(null);
        
        // Initialiser les DAOs
        produitDAO = new ProduitDAO();
        categorieDAO = new CategorieDAO();
        
        // Configurer le modèle de tableau
        configurerTableau();
        
        // Charger les données
        chargerCategories();
        chargerProduits();
        
        // Configurer les validations
        configurerValidations();
        
        // Ajouter les tooltips
        ajouterToolTips();
        
        // Configurer la recherche en temps réel
        configurerRecherche();
        
        // Initialiser en mode ajout
        activerModeAjout();
    }
    
    private void configurerTableau() {
        tableModel = (DefaultTableModel) jttableproduits.getModel();
        tableModel.setRowCount(0); // Vider le tableau
        
        // Créer un RowSorter pour le tri et la recherche
        sorter = new TableRowSorter<>(tableModel);
        jttableproduits.setRowSorter(sorter);
        
        // Configurer les largeurs de colonnes
        jttableproduits.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        jttableproduits.getColumnModel().getColumn(1).setPreferredWidth(200); // Nom
        jttableproduits.getColumnModel().getColumn(2).setPreferredWidth(120); // Catégorie
        jttableproduits.getColumnModel().getColumn(3).setPreferredWidth(100); // Prix
        jttableproduits.getColumnModel().getColumn(4).setPreferredWidth(80);  // Stock
        jttableproduits.getColumnModel().getColumn(5).setPreferredWidth(100); // Seuil
        jttableproduits.getColumnModel().getColumn(6).setPreferredWidth(80);  // Statut
    }
    
    private void chargerCategories() {
        try {
            jccategorie.removeAllItems();
            jccategorie.addItem("-- Sélectionnez une catégorie --");
            
            List<Categorie> categories = categorieDAO.getAllCategories();
            for (Categorie categorie : categories) {
                jccategorie.addItem(categorie.getLibelle());
            }
            
            if (jccategorie.getItemCount() == 1) {
                logger.warning("Aucune catégorie trouvée dans la base de données");
                JOptionPane.showMessageDialog(this, 
                    "Aucune catégorie trouvée.\nVeuillez d'abord créer des catégories.",
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            logger.severe("Erreur lors du chargement des catégories: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur lors du chargement des catégories: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void chargerProduits() {
        try {
            tableModel.setRowCount(0); // Vider le tableau
            
            List<Produit> produits = produitDAO.getAllProduits();
            for (Produit produit : produits) {
                String statut = "NORMAL";
                if (produit.getStockActuel() == 0) {
                    statut = "RUPTURE";
                } else if (produit.getStockActuel() <= produit.getSeuilAlerte()) {
                    statut = "ALERTE";
                }
                
                tableModel.addRow(new Object[]{
                    produit.getId(),
                    produit.getNom(),
                    produit.getCategorie().getLibelle(),
                    produit.getPrixVente(),
                    produit.getStockActuel(),
                    produit.getSeuilAlerte(),
                    statut
                });
            }
            
            if (tableModel.getRowCount() == 0) {
                logger.info("Aucun produit trouvé dans la base de données");
            } else {
                logger.info(tableModel.getRowCount() + " produits chargés");
            }
        } catch (Exception e) {
            logger.severe("Erreur lors du chargement des produits: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur lors du chargement des produits: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void configurerValidations() {
        // Empêcher les lettres dans les champs numériques
        txtPrix.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
                    e.consume();
                }
            }
        });
        
        txtStock.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
                    e.consume();
                }
            }
        });
        
        txtSeuilAlerte.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
                    e.consume();
                }
            }
        });
    }
    
    private void ajouterToolTips() {
        // Boutons de la barre d'outils
        jbajouter.setToolTipText("<html><b>Ajouter un nouveau produit</b><br>Remplissez le formulaire ci-dessous</html>");
        jbmodifier.setToolTipText("<html><b>Modifier le produit sélectionné</b><br>Sélectionnez d'abord un produit dans le tableau</html>");
        jbsupprimer.setToolTipText("<html><b>Supprimer le produit sélectionné</b><br>Sélectionnez d'abord un produit dans le tableau</html>");
        jbactualiser.setToolTipText("<html><b>Actualiser la liste des produits</b><br>Recharger les données depuis la base</html>");
        jbrechercher.setToolTipText("<html><b>Rechercher un produit</b><br>Cliquez pour lancer la recherche</html>");
        
        // Champs du formulaire
        txtNom.setToolTipText("<html><b>Nom du produit</b><br>Champ obligatoire</html>");
        jccategorie.setToolTipText("<html><b>Catégorie du produit</b><br>Sélectionnez une catégorie existante</html>");
        txtPrix.setToolTipText("<html><b>Prix de vente</b><br>• Doit être supérieur à 0<br>• Format: nombre décimal<br>• Exemple: 1500.50</html>");
        txtStock.setToolTipText("<html><b>Quantité en stock</b><br>• Doit être positive<br>• Exemple: 50</html>");
        txtSeuilAlerte.setToolTipText("<html><b>Seuil d'alerte</b><br>• Stock minimum avant alerte<br>• Exemple: 10</html>");
        jtrechercher.setToolTipText("<html><b>Recherche rapide</b><br>• Tapez pour rechercher par nom ou catégorie<br>• La recherche est instantanée</html>");
        
        // Boutons du formulaire
        jbenregistrer.setToolTipText("<html><b>Enregistrer les modifications</b><br>Valider le formulaire</html>");
        jbannuler.setToolTipText("<html><b>Annuler les modifications</b><br>Vider le formulaire</html>");
        jbreinitialiser.setToolTipText("<html><b>Réinitialiser le formulaire</b><br>Remettre à zéro tous les champs</html>");
        
        // Tableau
        jttableproduits.setToolTipText("<html><b>Liste des produits</b><br>• Double-cliquez sur une ligne pour la modifier<br>• Cliquez une fois pour la sélectionner</html>");
    }
    
    private void configurerRecherche() {
        // Recherche en temps réel
        jtrechercher.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrerTableau();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrerTableau();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrerTableau();
            }
        });
    }
    
    private void filtrerTableau() {
        String texte = jtrechercher.getText().toLowerCase();
        if (texte.trim().isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texte, 1, 2)); // Colonnes Nom et Catégorie
        }
    }
    
    private void activerModeAjout() {
        modeAjout = true;
        produitSelectionneId = -1;
        jbenregistrer.setText("Ajouter");
        reinitialiserFormulaire();
        jttableproduits.clearSelection();
    }
    
    private void activerModeModification(int id) {
        modeAjout = false;
        produitSelectionneId = id;
        jbenregistrer.setText("Modifier");
    }
    
    private void reinitialiserFormulaire() {
        txtNom.setText("");
        txtPrix.setText("");
        txtStock.setText("");
        txtSeuilAlerte.setText("5"); // Valeur par défaut
        if (jccategorie.getItemCount() > 0) {
            jccategorie.setSelectedIndex(0);
        }
    }
    
    private boolean validerFormulaire() {
        // Validation du nom
        if (txtNom.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un nom pour le produit.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            txtNom.requestFocus();
            return false;
        }
        
        // Validation de la catégorie
        if (jccategorie.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner une catégorie.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            jccategorie.requestFocus();
            return false;
        }
        
        // Validation du prix
        try {
            double prix = Double.parseDouble(txtPrix.getText().trim());
            if (prix <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "Le prix doit être supérieur à 0.",
                    "Erreur de validation",
                    JOptionPane.ERROR_MESSAGE);
                txtPrix.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un prix valide.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            txtPrix.requestFocus();
            return false;
        }
        
        // Validation du stock
        try {
            int stock = Integer.parseInt(txtStock.getText().trim());
            if (stock < 0) {
                JOptionPane.showMessageDialog(this, 
                    "Le stock ne peut pas être négatif.",
                    "Erreur de validation",
                    JOptionPane.ERROR_MESSAGE);
                txtStock.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir une quantité de stock valide.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            txtStock.requestFocus();
            return false;
        }
        
        // Validation du seuil d'alerte
        try {
            int seuil = Integer.parseInt(txtSeuilAlerte.getText().trim());
            if (seuil < 0) {
                JOptionPane.showMessageDialog(this, 
                    "Le seuil d'alerte ne peut pas être négatif.",
                    "Erreur de validation",
                    JOptionPane.ERROR_MESSAGE);
                txtSeuilAlerte.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un seuil d'alerte valide.",
                "Erreur de validation",
                JOptionPane.ERROR_MESSAGE);
            txtSeuilAlerte.requestFocus();
            return false;
        }
        
        return true;
    }
    
    private void enregistrerProduit() {
        if (!validerFormulaire()) {
            return;
        }
        
        try {
            // Récupérer la catégorie sélectionnée
            String categorieLibelle = (String) jccategorie.getSelectedItem();
            List<Categorie> categories = categorieDAO.getAllCategories();
            Categorie categorieSelectionnee = null;
            
            for (Categorie categorie : categories) {
                if (categorie.getLibelle().equals(categorieLibelle)) {
                    categorieSelectionnee = categorie;
                    break;
                }
            }
            
            if (categorieSelectionnee == null) {
                JOptionPane.showMessageDialog(this,
                    "Catégorie non trouvée.",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Créer l'objet Produit
            Produit produit = new Produit();
            produit.setNom(txtNom.getText().trim());
            produit.setCategorie(categorieSelectionnee);
            produit.setPrixVente(Double.parseDouble(txtPrix.getText().trim()));
            produit.setStockActuel(Integer.parseInt(txtStock.getText().trim()));
            produit.setSeuilAlerte(Integer.parseInt(txtSeuilAlerte.getText().trim()));
            
            boolean success;
            String message;
            
            if (modeAjout) {
                // Mode ajout
                success = produitDAO.addProduit(produit);
                message = success ? "Produit ajouté avec succès!" : "Erreur lors de l'ajout du produit.";
            } else {
                // Mode modification
                produit.setId(produitSelectionneId);
                success = produitDAO.updateProduit(produit);
                message = success ? "Produit modifié avec succès!" : "Erreur lors de la modification du produit.";
            }
            
            if (success) {
                JOptionPane.showMessageDialog(this, message, "Succès", JOptionPane.INFORMATION_MESSAGE);
                chargerProduits();
                activerModeAjout();
            } else {
                JOptionPane.showMessageDialog(this, message, "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            logger.severe("Erreur lors de l'enregistrement du produit: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Erreur lors de l'enregistrement: " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void supprimerProduit() {
        int selectedRow = jttableproduits.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner un produit à supprimer.",
                "Aucune sélection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Convertir l'index de la vue à l'index du modèle
        int modelRow = jttableproduits.convertRowIndexToModel(selectedRow);
        int id = (int) tableModel.getValueAt(modelRow, 0);
        String nom = (String) tableModel.getValueAt(modelRow, 1);
        
        int confirmation = JOptionPane.showConfirmDialog(this,
            "Êtes-vous sûr de vouloir supprimer le produit :\n\"" + nom + "\"?",
            "Confirmation de suppression",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirmation == JOptionPane.YES_OPTION) {
            try {
                boolean success = produitDAO.deleteProduit(id);
                if (success) {
                    JOptionPane.showMessageDialog(this,
                        "Produit supprimé avec succès!",
                        "Succès",
                        JOptionPane.INFORMATION_MESSAGE);
                    chargerProduits();
                    activerModeAjout();
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Erreur lors de la suppression du produit.\nLe produit est peut-être utilisé dans des commandes.",
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                logger.severe("Erreur lors de la suppression du produit: " + e.getMessage());
                JOptionPane.showMessageDialog(this,
                    "Erreur lors de la suppression: " + e.getMessage(),
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    
    
    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void jbajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbajouterActionPerformed
        activerModeAjout();
    }//GEN-LAST:event_jbajouterActionPerformed

    private void jbmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodifierActionPerformed
        int selectedRow = jttableproduits.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner un produit à modifier.",
                "Aucune sélection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Récupérer les données de la ligne sélectionnée
        int modelRow = jttableproduits.convertRowIndexToModel(selectedRow);
        int id = (int) tableModel.getValueAt(modelRow, 0);
        String nom = (String) tableModel.getValueAt(modelRow, 1);
        String categorie = (String) tableModel.getValueAt(modelRow, 2);
        double prix = (double) tableModel.getValueAt(modelRow, 3);
        int stock = (int) tableModel.getValueAt(modelRow, 4);
        int seuil = (int) tableModel.getValueAt(modelRow, 5);
        
        // Remplir le formulaire
        txtNom.setText(nom);
        
        // Sélectionner la catégorie dans la combo
        for (int i = 0; i < jccategorie.getItemCount(); i++) {
            if (jccategorie.getItemAt(i).equals(categorie)) {
                jccategorie.setSelectedIndex(i);
                break;
            }
        }
        
        txtPrix.setText(String.valueOf(prix));
        txtStock.setText(String.valueOf(stock));
        txtSeuilAlerte.setText(String.valueOf(seuil));
        
        // Activer le mode modification
        activerModeModification(id);
    }//GEN-LAST:event_jbmodifierActionPerformed

    private void jbsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsupprimerActionPerformed
        supprimerProduit();
    }//GEN-LAST:event_jbsupprimerActionPerformed

    private void jbactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbactualiserActionPerformed
        chargerProduits();
        chargerCategories();
        JOptionPane.showMessageDialog(this,
            "Liste des produits actualisée.",
            "Actualisation",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbactualiserActionPerformed

    private void jbrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrechercherActionPerformed
        filtrerTableau();
        if (jtrechercher.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Veuillez saisir un terme de recherche.",
                "Recherche",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbrechercherActionPerformed

    private void jbenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbenregistrerActionPerformed
        enregistrerProduit();
    }//GEN-LAST:event_jbenregistrerActionPerformed

    private void jbannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbannulerActionPerformed
        activerModeAjout();
        JOptionPane.showMessageDialog(this,
            "Opération annulée. Formulaire réinitialisé.",
            "Annulation",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbannulerActionPerformed

    private void jbreinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbreinitialiserActionPerformed
        reinitialiserFormulaire();
    }//GEN-LAST:event_jbreinitialiserActionPerformed

    private void jttableproduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jttableproduitsMouseClicked
        if (evt.getClickCount() == 2) { // Double-clic
            jbmodifierActionPerformed(null);
        }
    }//GEN-LAST:event_jttableproduitsMouseClicked

    private void initialiserDonnees() {
        // Vérifier la connexion à la base
        try {
            // Tenter de charger les catégories pour vérifier la connexion
            chargerCategories();
            logger.info("GestionProduitsForm initialisé avec succès");
        } catch (Exception e) {
            logger.severe("Erreur d'initialisation: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Impossible de se connecter à la base de données.\n" +
                "Veuillez vérifier que MySQL est démarré.\n\n" +
                "Erreur: " + e.getMessage(),
                "Erreur de connexion",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        // Utiliser le look and feel système
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            logger.log(java.util.logging.Level.WARNING, null, e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            GestionProduitsForm form = new GestionProduitsForm();
            form.setLocationRelativeTo(null); // Centrer la fenêtre
            form.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbactualiser;
    private javax.swing.JButton jbajouter;
    private javax.swing.JButton jbannuler;
    private javax.swing.JButton jbenregistrer;
    private javax.swing.JButton jbmodifier;
    private javax.swing.JButton jbrechercher;
    private javax.swing.JButton jbreinitialiser;
    private javax.swing.JButton jbsupprimer;
    private javax.swing.JComboBox<String> jccategorie;
    private javax.swing.JLabel jlFCFA;
    private javax.swing.JLabel jlSeuilalerte;
    private javax.swing.JLabel jlUnités;
    private javax.swing.JLabel jlcatégorie;
    private javax.swing.JLabel jlnom;
    private javax.swing.JLabel jlprix;
    private javax.swing.JLabel jlrechercher;
    private javax.swing.JLabel jlstock;
    private javax.swing.JPanel jpformulaire;
    private javax.swing.JScrollPane jscrollPane;
    private javax.swing.JTextField jtrechercher;
    private javax.swing.JTable jttableproduits;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtSeuilAlerte;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
