/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
/**
 *
 * @author logos
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setupWindow();
    }

    public String getLogin() {
    return jtlogin.getText().trim();
    }
    
    public String getPassword() {
    return new String(jptpassword.getPassword());
    }
    
    public boolean isRememberChecked() {
    return jcremember.isSelected();
    }
    
    public void showMessage(String message, boolean isError) {
    // Utiliser JOptionPane puisque jlmessage n'existe pas
    javax.swing.JOptionPane.showMessageDialog(this, 
        message, 
        isError ? "Erreur" : "Succès",
        isError ? javax.swing.JOptionPane.ERROR_MESSAGE : javax.swing.JOptionPane.INFORMATION_MESSAGE);
}

/**
 * Vide tous les champs du formulaire
 */
public void clearFields() {
    jtlogin.setText("");
    jptpassword.setText("");
}

/**
 * Ferme la fenêtre de connexion
 */
public void closeForm() {
    this.dispose();
}

/**
 * Centre la fenêtre et empêche le redimensionnement
 */
public void setupWindow() {
    setLocationRelativeTo(null); // Centrer
    setResizable(false); // Pas de redimensionnement
    setTitle("Connexion - Restaurant Management"); // Titre
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtlogin = new javax.swing.JTextField();
        jllogin = new javax.swing.JLabel();
        jlpassword = new javax.swing.JLabel();
        jcremember = new javax.swing.JCheckBox();
        jptpassword = new javax.swing.JPasswordField();
        jbconnexion = new javax.swing.JButton();
        jbannuler = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jltitre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtlogin.addActionListener(this::jtloginActionPerformed);

        jllogin.setText("Login : ");

        jlpassword.setText("Mot de passe :");

        jcremember.setText("Se souvenir de moi");
        jcremember.addActionListener(this::jcrememberActionPerformed);

        jptpassword.addActionListener(this::jptpasswordActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jllogin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlpassword)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jcremember))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jptpassword)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jllogin)
                    .addComponent(jtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpassword)
                    .addComponent(jptpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jcremember)
                .addGap(26, 26, 26))
        );

        jllogin.getAccessibleContext().setAccessibleName("JLabel");

        jbconnexion.setForeground(new java.awt.Color(51, 255, 51));
        jbconnexion.setText("Connexion");
        jbconnexion.addActionListener(this::jbconnexionActionPerformed);

        jbannuler.setForeground(new java.awt.Color(255, 0, 0));
        jbannuler.setText("Annuler");
        jbannuler.addActionListener(this::jbannulerActionPerformed);

        jltitre.setText("Connexion - Restaurant Managment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jltitre, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltitre, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbconnexion)
                .addGap(28, 28, 28)
                .addComponent(jbannuler)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbconnexion)
                    .addComponent(jbannuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtloginActionPerformed
        // TODO add your handling code here:
        jptpassword.requestFocus();
    }//GEN-LAST:event_jtloginActionPerformed

    private void jcrememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcrememberActionPerformed
        // TODO add your handling code here:
        System.out.println("Se souvenir de moi: " + jcremember.isSelected());
    }//GEN-LAST:event_jcrememberActionPerformed

    private void jbconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconnexionActionPerformed
        // TODO add your handling code here:
        try {
        // Créer et utiliser le contrôleur
        LoginController controller = new LoginController(this);
        controller.authenticate();
    } catch (Exception e) {
        // Afficher l'erreur dans la console pour déboguer
        System.err.println("Erreur lors de la connexion: " + e.getMessage());
        e.printStackTrace();
        
        // Afficher un message d'erreur simple
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Erreur: " + e.getMessage(), 
            "Erreur de connexion", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jbconnexionActionPerformed

    private void jbannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbannulerActionPerformed
        // TODO add your handling code here:
        try {
        LoginController controller = new LoginController(this);
        controller.cancel();
    } catch (Exception e) {
        System.err.println("Erreur lors de l'annulation: " + e.getMessage());
    }
    }//GEN-LAST:event_jbannulerActionPerformed

    private void jptpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jptpasswordActionPerformed
        // TODO add your handling code here:
        jbconnexionActionPerformed(evt);
    }//GEN-LAST:event_jptpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    private javax.swing.JLabel jlmessage;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbannuler;
    private javax.swing.JButton jbconnexion;
    private javax.swing.JCheckBox jcremember;
    private javax.swing.JLabel jllogin;
    private javax.swing.JLabel jlpassword;
    private javax.swing.JLabel jltitre;
    private javax.swing.JPasswordField jptpassword;
    private javax.swing.JTextField jtlogin;
    // End of variables declaration//GEN-END:variables
}
